/**
 * 
 * #   #   ###  #####  #####
 * ##  #  #   #   #    #
 * # # #  #   #   #    ####
 * #  ##  #   #   #    #
 * #   #   ###    #    #####
 * 
 * This code was generated by Google.llc Gemini, 
 * so there aren't ANY GUARANTEE IT WILL WORK PROPERLY
 * 
 * P.S Deadline is too short to complete all tasks
 * (10 days sometimes not enough)
 * 
 * 
 * 
 * 
 * 
 * File: SHOP.dat
 * data:War and Peace;Leo Tolstoy;1;1869;550.00
 * 1984;George Orwell;6;1949;400.99
 * Kobzar;Taras Shevchenko;3;1840;300.50
 */


#include <iostream>
#include <fstream>
#include <string.h>
#include <iomanip>
#include <algorithm>


using namespace std;

struct Date {
    int month;
    int year;
};

struct BOOK {
    char Name[50];
    char Avtor[50];
    Date Data;
    double Cost;
};

class Node {
public:
    BOOK data;
    Node* next;
    Node(const BOOK& book) : data(book), next(nullptr) {}
};

class BookList {
private:
    Node* head;
    
    void cleanup() {
        Node* current = head;
        while (current != nullptr) {
            Node* next = current->next;
            delete current;
            current = next;
        }
        head = nullptr;
    }

public:
    BookList() : head(nullptr) {}

    ~BookList() {
        cleanup();
    }

    void append(const BOOK& book) {
        Node* newNode = new Node(book);
        if (head == nullptr) {
            head = newNode;
            return;
        }
        Node* current = head;
        while (current->next != nullptr) {
            current = current->next;
        }
        current->next = newNode;
    }

    void print() const {
        if (head == nullptr) {
            cout << "The list is empty." << endl;
            return;
        }
        cout << "\n--- Book List ---" << endl;
        cout << left << setw(50) << "Name" << setw(50) << "Author" 
             << setw(10) << "Date (M/Y)" << setw(10) << "Cost" << endl;
        cout << string(120, '-') << endl;
        
        Node* current = head;
        while (current != nullptr) {
            cout << left << setw(50) << current->data.Name 
                 << setw(50) << current->data.Avtor 
                 << setw(2) << current->data.Data.month << "/" 
                 << setw(7) << current->data.Data.year 
                 << fixed << setprecision(2) << setw(10) << current->data.Cost << endl;
            current = current->next;
        }
        cout << "--------------------" << endl;
    }

    void deleteByYear(int year) {
        if (head == nullptr) return;

        Node* current = head;
        Node* prev = nullptr;
        int count = 0;

        while (head != nullptr && head->data.Data.year == year) {
            Node* temp = head;
            head = head->next;
            delete temp;
            count++;
        }

        current = head;
        while (current != nullptr) {
            if (current->data.Data.year == year) {
                Node* temp = current;
                prev->next = current->next;
                current = current->next;
                delete temp;
                count++;
            } else {
                prev = current;
                current = current->next;
            }
        }
        cout << "Deleted " << count << " book(s) published in " << year << "." << endl;
    }

    void loadFromTextFile(const string& filename) {
        ifstream file(filename);
        if (!file.is_open()) {
            cerr << "Error: Could not open file " << filename << endl;
            return;
        }

        cout << "\n--- Reading data from " << filename << " ---" << endl;
        string line;
        while (getline(file, line)) {
            BOOK book;
            size_t p1, p2, p3, p4;

            p1 = line.find(';');
            p2 = line.find(';', p1 + 1);
            p3 = line.find(';', p2 + 1);
            p4 = line.find(';', p3 + 1);

            if (p1 == string::npos || p2 == string::npos || p3 == string::npos || p4 == string::npos) continue;

            try {
                strncpy(book.Name, line.substr(0, p1).c_str(), 49); book.Name[49] = '\0';
                strncpy(book.Avtor, line.substr(p1 + 1, p2 - p1 - 1).c_str(), 49); book.Avtor[49] = '\0';
                
                book.Data.month = stoi(line.substr(p2 + 1, p3 - p2 - 1));
                book.Data.year = stoi(line.substr(p3 + 1, p4 - p3 - 1));
                book.Cost = stod(line.substr(p4 + 1));
                
                this->append(book);
            } catch (...) {
                cerr << "Error converting data in line: " << line << endl;
            }
        }
        file.close();
    }
    
    void addNewBooks(int N) {
        cout << "\n--- Adding " << N << " new books ---" << endl;
        for (int i = 0; i < N; ++i) {
            BOOK book;
            cout << "Book #" << i + 1 << ":" << endl;
            cout << " Name: ";
            cin.ignore(); 
            cin.getline(book.Name, 50);
            cout << " Author: ";
            cin.getline(book.Avtor, 50);
            cout << " Print Month: ";
            cin >> book.Data.month;
            cout << " Print Year: ";
            cin >> book.Data.year;
            cout << " Cost: ";
            cin >> book.Cost;

            this->append(book);
        }
    }

    void saveToBinaryFile(const string& filename) const {
        ofstream file(filename, ios::binary | ios::out);
        if (!file.is_open()) {
            cerr << "Error: Could not open binary file " << filename << " for writing." << endl;
            return;
        }

        Node* current = head;
        while (current != nullptr) {
            file.write((char*)&current->data, sizeof(BOOK));
            current = current->next;
        }

        file.close();
        cout << "\nList successfully written to binary file: " << filename << endl;
    }
};

bool compareByAuthor(const BOOK& a, const BOOK& b) {
    return strcmp(a.Avtor, b.Avtor) < 0;
}

void processBinaryFile(const string& binaryFilename, const string& outputFilename) {
    BOOK lastTenBooks[10];
    int count = 0;

    ifstream file(binaryFilename, ios::binary | ios::in | ios::ate); 
    if (!file.is_open()) {
        cerr << "Error: Could not open binary file " << binaryFilename << " for reading." << endl;
        return;
    }

    streampos fileSize = file.tellg();
    long bookSize = sizeof(BOOK);
    int totalBooks = fileSize / bookSize;
    int booksToRead = min(10, totalBooks);
    
    streampos startPos = fileSize - (streampos)booksToRead * bookSize;
    if (startPos < 0) startPos = 0;

    file.seekg(startPos, ios::beg);

    while (count < booksToRead && file.read((char*)&lastTenBooks[count], bookSize)) {
        count++;
    }
    file.close();

    cout << "\nRead " << count << " last books from binary file." << endl;

    if (count == 0) {
        cout << "Not enough data to sort and write." << endl;
        return;
    }

    sort(lastTenBooks, lastTenBooks + count, compareByAuthor);

    ofstream outFile(outputFilename);
    if (!outFile.is_open()) {
        cerr << "Error: Could not open file " << outputFilename << " for writing." << endl;
        return;
    }

    outFile << left << setw(50) << "Name" << setw(50) << "Author" 
            << setw(10) << "Date (M/Y)" << setw(10) << "Cost" << endl;
    outFile << string(120, '=') << endl;
    
    for (int i = 0; i < count; ++i) {
        outFile << left << setw(50) << lastTenBooks[i].Name 
                << setw(50) << lastTenBooks[i].Avtor 
                << setw(2) << lastTenBooks[i].Data.month << "/" 
                << setw(7) << lastTenBooks[i].Data.year 
                << fixed << setprecision(2) << setw(10) << lastTenBooks[i].Cost << endl;
    }

    outFile.close();
    cout << "Sorted data for " << count << " books written to file " << outputFilename << endl;
}

int main() {
    
    BookList myBookShop;

    // ===== Part 2: List Operations =====
    cout << "===== Part 2: List Operations =====" << endl;

    myBookShop.loadFromTextFile("SHOP.dat");
    myBookShop.print();
    

    int yearToDelete;
    cout << "\nEnter the year of publication to delete books: ";
    cin >> yearToDelete;
    myBookShop.deleteByYear(yearToDelete);
    myBookShop.print();

    int N;
    cout << "\nEnter the number of new books to add (N): ";
    cin >> N;
    myBookShop.addNewBooks(N);
    myBookShop.print();

    myBookShop.saveToBinaryFile("SHOP_NEW.DAT");
    
    // ===== Part 3: Binary File Operations =====
    cout << "\n===== Part 3: Binary File Operations =====" << endl;

    processBinaryFile("SHOP_NEW.DAT", "BOOK.DAT");

    cout << "\nProgram finished execution." << endl;

    return 0;
}